Please login with your login and password:
    <hr />
	<form action="index.php" method="post">
    <table width="150">
    <tr>
    <td align="left">Login: </td>
    <td> <input name="login" type="text" size="13" /></td>
		
     </tr>
     <tr>
     <td align="left"> Password: </td>
     <td><input name="password" type="password" size="13" />
     </td>
     </tr>
         <tr>
         	
         
         <td align="left">
           <input name="remember" type="checkbox" value="Remember" align="left" /> Remember?
           
          </td>
          <td align="right">
           <input name="submit" type="submit" value="Submit" />
     	  </td>
     	</tr>
        <tr>
        <td colspan="2">
        </td>
     
     </table>
    </form>






